src/gradient/abs_value.v
src/gradient/gradient_datpath.v
src/gradient/gradient_decision_tree.v
src/gradient/mag_aprox.v
src/gradient/sobel_filter.v
src/multiplier/cla_4bit.v
src/multiplier/cla_adder.v
src/multiplier/csa_16bit.v
src/multiplier/full_adder.v
src/multiplier/gauss_smoothing_datapath.v
src/multiplier/gauss_uc.v
src/multiplier/gauss_uc.v
src/multiplier/half_adder.v
src/multiplier/wallace_8x8_unsigned.v
src/window/line_buffer.v
src/window/sliding_window_3x3.v
src/window/sliding_window_7x7_flex.v
src/window/sliding_window_fsm.v
src/window/nms_window_buffer.v
src/NMS/nms_combinational.v
src/thresholding/double_threshold.v
src/thresholding/hysteresis_logic.v
src/thresholding/hysteresis_datapath.v
src/noise_estimator/noise_estimator_uc.v
src/noise_estimator/noise_estimator.v
src/config_table/config_table.v
src/rgb_gray_average.v
src/Canny_top/canny_top_module.v
//
//    TESTBENCHS
//
//src/NMS/tb_nms_combinational.v
//src/window/tb_line_buffer.v
src/window/tb_window_3x3.v
//src/window/tb_window_7x7_flex.v
//src/window/tb_nms_buffer.v
//src/gradient/tb_gradient_datapath.v
//src/multiplier/tb_wallace.v
//src/multiplier/tb_image_filter.v
//src/thresholding/tb_double_threshold.v
//src/thresholding/tb_hysteresis_logic.v/
//src/thresholding/tb_hysteresis_datapath.v
//src/Canny_top/tb_canny_top_module.v